//https://www.boredpanda.com/animal-sounds-different-languages-james-chapman/?utm_source=google&utm_medium=organic&utm_campaign=organic
export const HomeObj = [
  {
    id: "japan",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Japanese - nyan (にゃん)",
    symbol: "meong",
    headline: "in Japanese",
    description:
      'In Japanese, nya にゃ, nyan にゃん, or nyaa にゃー (also spelled にゃあ and にゃぁ), or "nyah" are onomatopoeia that mean "meow", the sound that cats make.',
    buttonLabel: "Learn more",
    imgStart: true,
    img: require("../../assets/images/cat-1.svg"),
    alt: "cat-1",
    dark: true,
    primary: true,
    darkText: false,
    padding: 172,
    goto: "https://en.wikipedia.org/wiki/Nyan_Cat",
    section: "#home",
  },
  {
    id: "china",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Chinese - miao (喵)",
    symbol: "nyan (にゃん)",
    headline: "in Chinese",
    description:
      "The word for cat practically mewls itself: it’s māo 猫, which is also a close homophone of the word for fur or hair, máo 毛, all of which is just as ubiquitous as their miāoing. In addition to meowing, cats can also cèng 蹭, which is when they headbutt/rub up against you (or a table, or a door, or anything as yet unmarked).",
    buttonLabel: "Learn more",
    imgStart: false,
    img: require("../../assets/images/cat-2.svg"),
    alt: "cat-2",
    dark: false,
    primary: false,
    darkText: true,
    padding: 174,
    goto: "https://chinachannel.org/2018/03/20/meowing-in-mandarin/",
    section: "#japan",
  },
  {
    id: "urdu",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Urdu - miyāʾūṉ (میاٴوں)",
    symbol: "miao (喵)",
    headline: "in urdu (pakistan)",
    description:
      'Meowing meaning in Urdu is Miyaun. Similar words of Meowing are also commonly used in daily talk like as Meow. Pronunciation of Meowing in roman Urdu is "Miyaun" and Translation of Meowing in Urdu writing script is میاٴوں.',
    buttonLabel: "Learn more",
    imgStart: true,
    img: require("../../assets/images/cat-3.svg"),
    alt: "cat-3",
    dark: true,
    primary: true,
    darkText: false,
    padding: 189,
    goto: "https://hamariweb.com/dictionaries/meowing_urdu-meanings.aspx",
    section: "#china",
  },
  {
    id: "rusia",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Russian - miyau (мяу)",
    symbol: "miyāʾūṉ (میاٴوں)",
    headline: "in russian",
    description: `How do cats sound in russian?, yes it's miyau (мяу)`,
    buttonLabel: "Learn more",
    imgStart: false,
    img: require("../../assets/images/cat-4.svg"),
    alt: "cat-4",
    dark: false,
    primary: false,
    darkText: true,
    padding: 191,
    goto: "https://about.imtranslator.net/onomatopoeia-in-russian-language/",
    section: "#urdu",
  },
];
